### ISSUE TITLE
Have question !!!

### ISSUE THREAD

**Issue by SudoDios** [kirill-grouchnikov/artemis#1]
Hi.
I want to learn skls professionally.
Where can I start ?

**Comment by kirill-grouchnikov** [comment]
This is not the right place to ask general questions about shaders

**Comment by SudoDios** [comment]
So where should I ask?

**Comment by kirill-grouchnikov** [comment]
There’s Skia mailing lists for Skia specific questions, and various tutorials and forums that you might research online.

**Comment by SudoDios** [comment]
Thank you
